services:
  fastapi:
    build: .
    container_name: bookworm_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:496226104MyKi@host.docker.internal:5432/bookworm"
      REDIS_HOST: "redis"
      MINIO_HOST: "minio"
      MINIO_ACCESS_KEY: "your-access-key"
      MINIO_SECRET_KEY: "your-secret-key"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "your-access-key"
      MINIO_ROOT_PASSWORD: "your-secret-key"
